export const SET_YIELD = "SET_YIELD";
export const CLEAR_YIELD = "CLEAR_YIELD";
export const SET_CURPRICE = "SET_CURPRICE";

export const SET_DATE = "SET_DATE";

export const SET_DATA_SUFFICIENCY = "SET_DATA_SUFFICIENCY";

export const SET_PRICE_INPUT = "SET_PRICE_INPUT";
export const CLEAR_PRICE_INPUT = "CLEAR_PRICE_INPUT";
